item {
  id: 1
  name: "Jack Link's Original Beef Jerky 1.25oz"
}

item {
  id: 2
  name: "Jack Link's Teriyaki Beef Jerky 1.25oz"
}

item {
  id: 3
  name: "Jack Link's Sweet and Hot Beef Jerky 3.25oz"
}

item {
  id: 4
  name: "Jack Link's Peppered Beef Jerky 3.25oz"
}
